### ISSUE TITLE
ATTENTION ATTENTION ATTENTION!!!

### ISSUE THREAD

**Issue by sponges** [AlexFlipnote/Discord_CatBot#4]
ATTENTION ATTENTION ATTENTION!!! Ladies and gentlemen Boys and Girls Brothers and sisters Father and Mothers Uncles and aunties Nephews and nieces Doctors and nurses Neighbours and Colleagues Students and graduates. I really don't have anything to say. Thanks for your attention.

**Comment by AlexFlipnote** [comment]
*clap clap*

**Comment by sponges** [comment]
thx atleast i tried
